apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/gpu_plugin
    repoURL: https://github.com/intel/intel-device-plugins-for-kubernetes.git
    targetRevision: v0.24.0
  syncPolicy: {}
